# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KHoFj8AskZ4mnRejwcrHdxCrCUinFL0q
"""

import streamlit as st
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
import pandas as pd

# Sample movie data
movie_data = {
    'title': ['Movie 1', 'Movie 2', 'Movie 3', 'Movie 4', 'Movie 5'],
    'description': [
        'A group of friends embark on a journey to save the world.',
        'A young boy discovers he has magical powers.',
        'An epic tale of love and betrayal set in ancient times.',
        'A comedy about a dysfunctional family on vacation.',
        'A thriller about a detective solving a murder mystery.'
    ]
}

# Create DataFrame from movie data
df = pd.DataFrame(movie_data)

# Vectorize movie descriptions
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(df['description'])

# Perform K-means clustering
k = 2  # Number of clusters
kmeans = KMeans(n_clusters=k)
kmeans.fit(X)
df['cluster'] = kmeans.labels_

# Display clustered movies
st.title('Movie Clustering')

for cluster_id in range(k):
    st.subheader(f'Cluster {cluster_id + 1}')
    cluster_movies = df[df['cluster'] == cluster_id]['title'].tolist()
    for movie in cluster_movies:
        st.write(movie)

